### ISSUE TITLE
About training scripts.

### ISSUE THREAD

**Issue by ElliottYan** [samuki/reinforce-joey#1]
Hi, 
Thanks for sharing your code. 

I plan to reproduce your results for RL methods in your paper. 
However, in my previous experiments, I find it non-trivial to reproduce the results of models like MRT or RL in NMT, where it needs careful tuning of hyper-parameters to make these methods work. 

I'm wondering if you can release some of your training scripts to help reproduce the results?

**Comment by samuki** [comment]
Hi, 
thanks a lot for your interest! 

Yes, the models are very sensitive to hyper-parameters!
I uploaded example configs for MRT and PG in the [configs directory](https://github.com/samuki/reinforce-joey/tree/master/configs).  
You can then select them during training, e.g. `python3 -m joeynmt train configs/mrt_cross_domain.yaml`  
The training procedure is described in the official [Joey NMT repository](https://github.com/joeynmt/joeynmt#training) or in greater detail in the [documentation](https://joeynmt.readthedocs.io/en/latest/tutorial.html#training).

**Comment by ElliottYan** [comment]
> Hi,
> thanks a lot for your interest!
> 
> Yes, the models are very sensitive to hyper-parameters!
> I uploaded example configs for MRT and PG in the [configs directory](https://github.com/samuki/reinforce-joey/tree/master/configs).
> You can then select them during training, e.g. `python3 -m joeynmt train configs/mrt_cross_domain.yaml`
> The training procedure is described in the official [Joey NMT repository](https://github.com/joeynmt/joeynmt#training) or in greater detail in the [documentation](https://joeynmt.readthedocs.io/en/latest/tutorial.html#training).

Great! Thanks for sharing!
